### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by bokko-chan** [bokko-chan/protospace-31049#1]
# URL
https://protospace-31049.herokuapp.com/

**Comment by tech-taro** [comment]
bokko-chanさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by bokko-chan** [comment]
tech-taroさんご確認ありがとうございます。
Slackに案内もいただきました。
宜しくお願いいたします。
